### ISSUE TITLE
ignore the ssl certificate errors so that sites with self-signed certificates can be checked for availability

### ISSUE THREAD

**Issue by danionescu2007** [brotandgames/ciao#139] opened 2022-07-24 20:21 UTC
**Is your feature request related to a problem? Please describe.**
the checks against https with a self-signed certificate fails.

**Describe the solution you'd like**
ignore the ssl certificate validation so that those check will check the connection/availability of the service, not the certificate

**Describe alternatives you've considered**
ignore the ssl certificate errors

**Additional context**
<img width="738" alt="image" src="https://user-images.githubusercontent.com/4688610/180664414-b9fc1734-2b5e-4766-8ebb-16acde9d3f12.png">

**Comment by brotandgames** [comment] 2022-10-09 19:17
Duplicate of #28.

Ignoring SSL certificate errors is not in the scope of this project. There are ways to let ciao trust self-signed certificates, one of them described in this comment https://github.com/brotandgames/ciao/issues/28#issuecomment-517901990.

**Closed by brotandgames** 2022-10-09 19:17 UTC

**Comment by mignz** [comment] 2022-12-27 06:54
Sorry for digging this, but I also feel that this should be a feature. Ciao is such a simple service and having to trust a self-signed certificates every time a Docker container gets updated, for example, and unfortunately some of them do create new certificates, is far from simple.

Also a 401 response is, some times, the correct response if the user is not signed in. Ciao shows these with a yellow badge and calls the eye, when it's just the way it should be.
