### ISSUE TITLE
Disable certificate verification

### ISSUE THREAD

**Issue by sebw** [brotandgames/ciao#88] opened 2020-09-30 20:49 UTC
I want to monitor things on my home network and some devices use self-signed certificates.

It would be nice to be able to disable certificate validation per check.

**Comment by brotandgames** [comment] 2020-10-01 14:25
@sebw This is not in the scope of this project.

Possible solution(s) for your usecase: https://github.com/brotandgames/ciao/issues/28#issuecomment-517901389

**Comment by brotandgames** [comment] 2020-10-01 14:44
Duplicate of #28

**Closed by brotandgames** 2020-10-01 14:44 UTC
